version: '3.8'  # Specify your version

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "yuval"
      POSTGRES_DB: AirTrackerDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://yuval:admin@postgres:5432/AirTrackerDatabase"
    volumes:
      - ./backend:/app/server
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:5000/health || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./web:/web

volumes:
  postgres_data:
