version: '3.8'  # Specify the Docker Compose version

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "yuval"
      POSTGRES_DB: AirTrackerDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
